/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasprintjava;

import java.awt.Button;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.*;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame {

    private String Prov;
    private int Cine = 0;
    private int Movie = 0;
    private String Seat = "";
    private double Price = 0;
    private double Amount = 0;
    
    private List<String> lstSeat = new ArrayList<String>();
    private List<String> bookedSeat = new ArrayList<String>();
    private String[] seatButtons = {"A1","A2","A3","A4","A5","A6","A7","A8","A9","A10",
        "B1","B2","B3","B4","B5","B6","B7","B8","B9","B10",
        "C1","C2","C3","C4","C5","C6","C7","C8","C9","C10",
        "D1","D2","D3","D4","D5","D6","D7","D8","D9","D10",
        "E1","E2","E3","E4","E5","E6","E7","E8","E9","E10",
        "F1","F2","F3","F4","F5","F6","F7","F8","F9","F10"};
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAddSeat = new javax.swing.JButton();
        edtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRemoveSeats = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtSeats = new javax.swing.JTextArea();
        pnlSelection = new javax.swing.JPanel();
        cmbProvince = new javax.swing.JComboBox<>();
        cmbCinema = new javax.swing.JComboBox<>();
        cmbMovie = new javax.swing.JComboBox<>();
        edtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtSeat = new javax.swing.JTextField();
        cmbTime = new javax.swing.JComboBox<>();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        pnl1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        button23 = new java.awt.Button();
        button24 = new java.awt.Button();
        button25 = new java.awt.Button();
        button26 = new java.awt.Button();
        button27 = new java.awt.Button();
        button28 = new java.awt.Button();
        button29 = new java.awt.Button();
        button30 = new java.awt.Button();
        button31 = new java.awt.Button();
        button32 = new java.awt.Button();
        button33 = new java.awt.Button();
        button34 = new java.awt.Button();
        button35 = new java.awt.Button();
        button36 = new java.awt.Button();
        button37 = new java.awt.Button();
        button38 = new java.awt.Button();
        button39 = new java.awt.Button();
        button40 = new java.awt.Button();
        button41 = new java.awt.Button();
        button42 = new java.awt.Button();
        button43 = new java.awt.Button();
        button44 = new java.awt.Button();
        button45 = new java.awt.Button();
        button46 = new java.awt.Button();
        button47 = new java.awt.Button();
        button48 = new java.awt.Button();
        button49 = new java.awt.Button();
        button50 = new java.awt.Button();
        button51 = new java.awt.Button();
        button52 = new java.awt.Button();
        button53 = new java.awt.Button();
        button54 = new java.awt.Button();
        button55 = new java.awt.Button();
        button56 = new java.awt.Button();
        button57 = new java.awt.Button();
        button58 = new java.awt.Button();
        button59 = new java.awt.Button();
        button60 = new java.awt.Button();
        pnl2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBooked = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        btn65 = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        btn70 = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        btn75 = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Movies are our business");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Cinematics");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnBook.setText("Book");
        btnBook.setToolTipText("");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 104, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 100, -1));

        btnAddSeat.setText("Add Seat");
        btnAddSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSeatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 100, -1));

        edtTotal.setEditable(false);
        edtTotal.setText("R 0.00");
        getContentPane().add(edtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        btnRemoveSeats.setText("Remove Seats");
        btnRemoveSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSeatsActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        jLabel6.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 250, 250));
        jLabel6.setText("---------------------SCREEN---------------------");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        edtSeats.setColumns(20);
        edtSeats.setRows(5);
        jScrollPane1.setViewportView(edtSeats);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 431, 86));

        pnlSelection.setOpaque(false);
        pnlSelection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbProvince.setMaximumRowCount(4);
        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Province>", "Eastern Cape", "The Free State", "Gauteng", "Kwazulu Natal", "Limpopo", "Mpumalanga", "Northern Cape", "North West", "Western Cape" }));
        cmbProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinceActionPerformed(evt);
            }
        });
        pnlSelection.add(cmbProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmbCinema.setMaximumRowCount(4);
        cmbCinema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Cinema>" }));
        cmbCinema.setToolTipText("");
        cmbCinema.setEnabled(false);
        cmbCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCinemaActionPerformed(evt);
            }
        });
        pnlSelection.add(cmbCinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 114, -1));

        cmbMovie.setMaximumRowCount(4);
        cmbMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Movie>" }));
        cmbMovie.setEnabled(false);
        cmbMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovieActionPerformed(evt);
            }
        });
        pnlSelection.add(cmbMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 114, -1));

        edtPrice.setEditable(false);
        edtPrice.setText("R 0.00");
        pnlSelection.add(edtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Price:");
        pnlSelection.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Seat:");
        pnlSelection.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        edtSeat.setEditable(false);
        pnlSelection.add(edtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 86, -1));

        cmbTime.setMaximumRowCount(4);
        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select time>", "09:00", "12:00", "15:00", "18:00", "21:00" }));
        cmbTime.setEnabled(false);
        cmbTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTimeActionPerformed(evt);
            }
        });
        pnlSelection.add(cmbTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jXDatePicker1.setOpaque(true);
        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        pnlSelection.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        getContentPane().add(pnlSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 470, 130));

        pnl1.setOpaque(false);
        pnl1.setLayout(new java.awt.GridLayout(6, 10, 2, 8));

        button1.setBackground(new java.awt.Color(0, 51, 51));
        button1.setForeground(new java.awt.Color(250, 250, 250));
        button1.setLabel("A1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pnl1.add(button1);

        button2.setBackground(new java.awt.Color(0, 51, 51));
        button2.setForeground(new java.awt.Color(250, 250, 250));
        button2.setLabel("A2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        pnl1.add(button2);

        button3.setBackground(new java.awt.Color(0, 51, 51));
        button3.setForeground(new java.awt.Color(250, 250, 250));
        button3.setLabel("A3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        pnl1.add(button3);

        button4.setBackground(new java.awt.Color(0, 51, 51));
        button4.setForeground(new java.awt.Color(250, 250, 250));
        button4.setLabel("A4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        pnl1.add(button4);

        button5.setBackground(new java.awt.Color(0, 51, 51));
        button5.setForeground(new java.awt.Color(250, 250, 250));
        button5.setLabel("A5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        pnl1.add(button5);

        button6.setBackground(new java.awt.Color(0, 51, 51));
        button6.setForeground(new java.awt.Color(250, 250, 250));
        button6.setLabel("A6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        pnl1.add(button6);

        button7.setBackground(new java.awt.Color(0, 51, 51));
        button7.setForeground(new java.awt.Color(250, 250, 250));
        button7.setLabel("A7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        pnl1.add(button7);

        button8.setBackground(new java.awt.Color(0, 51, 51));
        button8.setForeground(new java.awt.Color(250, 250, 250));
        button8.setLabel("A8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        pnl1.add(button8);

        button9.setBackground(new java.awt.Color(0, 51, 51));
        button9.setForeground(new java.awt.Color(250, 250, 250));
        button9.setLabel("A9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        pnl1.add(button9);

        button10.setBackground(new java.awt.Color(0, 51, 51));
        button10.setForeground(new java.awt.Color(250, 250, 250));
        button10.setLabel("A10");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        pnl1.add(button10);

        button11.setBackground(new java.awt.Color(0, 51, 51));
        button11.setForeground(new java.awt.Color(250, 250, 250));
        button11.setLabel("B1");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        pnl1.add(button11);

        button12.setBackground(new java.awt.Color(0, 51, 51));
        button12.setForeground(new java.awt.Color(250, 250, 250));
        button12.setLabel("B2");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        pnl1.add(button12);

        button13.setBackground(new java.awt.Color(0, 51, 51));
        button13.setForeground(new java.awt.Color(250, 250, 250));
        button13.setLabel("B3");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        pnl1.add(button13);

        button14.setBackground(new java.awt.Color(0, 51, 51));
        button14.setForeground(new java.awt.Color(250, 250, 250));
        button14.setLabel("B4");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        pnl1.add(button14);

        button15.setBackground(new java.awt.Color(0, 51, 51));
        button15.setForeground(new java.awt.Color(250, 250, 250));
        button15.setLabel("B5");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        pnl1.add(button15);

        button16.setBackground(new java.awt.Color(0, 51, 51));
        button16.setForeground(new java.awt.Color(250, 250, 250));
        button16.setLabel("B6");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        pnl1.add(button16);

        button17.setBackground(new java.awt.Color(0, 51, 51));
        button17.setForeground(new java.awt.Color(250, 250, 250));
        button17.setLabel("B7");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        pnl1.add(button17);

        button18.setBackground(new java.awt.Color(0, 51, 51));
        button18.setForeground(new java.awt.Color(250, 250, 250));
        button18.setLabel("B8");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        pnl1.add(button18);

        button19.setBackground(new java.awt.Color(0, 51, 51));
        button19.setForeground(new java.awt.Color(250, 250, 250));
        button19.setLabel("B9");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        pnl1.add(button19);

        button20.setBackground(new java.awt.Color(0, 51, 51));
        button20.setForeground(new java.awt.Color(250, 250, 250));
        button20.setLabel("B10");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        pnl1.add(button20);

        button21.setBackground(new java.awt.Color(51, 0, 51));
        button21.setForeground(new java.awt.Color(250, 250, 250));
        button21.setLabel("C1");
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        pnl1.add(button21);

        button22.setBackground(new java.awt.Color(51, 0, 51));
        button22.setForeground(new java.awt.Color(250, 250, 250));
        button22.setLabel("C2");
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        pnl1.add(button22);

        button23.setBackground(new java.awt.Color(51, 0, 51));
        button23.setForeground(new java.awt.Color(250, 250, 250));
        button23.setLabel("C3");
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        pnl1.add(button23);

        button24.setBackground(new java.awt.Color(51, 0, 51));
        button24.setForeground(new java.awt.Color(250, 250, 250));
        button24.setLabel("C4");
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        pnl1.add(button24);

        button25.setBackground(new java.awt.Color(51, 0, 51));
        button25.setForeground(new java.awt.Color(250, 250, 250));
        button25.setLabel("C5");
        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });
        pnl1.add(button25);

        button26.setBackground(new java.awt.Color(51, 0, 51));
        button26.setForeground(new java.awt.Color(250, 250, 250));
        button26.setLabel("C6");
        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });
        pnl1.add(button26);

        button27.setBackground(new java.awt.Color(51, 0, 51));
        button27.setForeground(new java.awt.Color(250, 250, 250));
        button27.setLabel("C7");
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        pnl1.add(button27);

        button28.setBackground(new java.awt.Color(51, 0, 51));
        button28.setForeground(new java.awt.Color(250, 250, 250));
        button28.setLabel("C8");
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });
        pnl1.add(button28);

        button29.setBackground(new java.awt.Color(51, 0, 51));
        button29.setForeground(new java.awt.Color(250, 250, 250));
        button29.setLabel("C9");
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        pnl1.add(button29);

        button30.setBackground(new java.awt.Color(51, 0, 51));
        button30.setForeground(new java.awt.Color(250, 250, 250));
        button30.setLabel("C10");
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        pnl1.add(button30);

        button31.setBackground(new java.awt.Color(51, 0, 51));
        button31.setForeground(new java.awt.Color(250, 250, 250));
        button31.setLabel("D1");
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });
        pnl1.add(button31);

        button32.setBackground(new java.awt.Color(51, 0, 51));
        button32.setForeground(new java.awt.Color(250, 250, 250));
        button32.setLabel("D2");
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button32ActionPerformed(evt);
            }
        });
        pnl1.add(button32);

        button33.setBackground(new java.awt.Color(51, 0, 51));
        button33.setForeground(new java.awt.Color(250, 250, 250));
        button33.setLabel("D3");
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button33ActionPerformed(evt);
            }
        });
        pnl1.add(button33);

        button34.setBackground(new java.awt.Color(51, 0, 51));
        button34.setForeground(new java.awt.Color(250, 250, 250));
        button34.setLabel("D4");
        button34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button34ActionPerformed(evt);
            }
        });
        pnl1.add(button34);

        button35.setBackground(new java.awt.Color(51, 0, 51));
        button35.setForeground(new java.awt.Color(250, 250, 250));
        button35.setLabel("D5");
        button35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button35ActionPerformed(evt);
            }
        });
        pnl1.add(button35);

        button36.setBackground(new java.awt.Color(51, 0, 51));
        button36.setForeground(new java.awt.Color(250, 250, 250));
        button36.setLabel("D6");
        button36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button36ActionPerformed(evt);
            }
        });
        pnl1.add(button36);

        button37.setBackground(new java.awt.Color(51, 0, 51));
        button37.setForeground(new java.awt.Color(250, 250, 250));
        button37.setLabel("D7");
        button37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button37ActionPerformed(evt);
            }
        });
        pnl1.add(button37);

        button38.setBackground(new java.awt.Color(51, 0, 51));
        button38.setForeground(new java.awt.Color(250, 250, 250));
        button38.setLabel("D8");
        button38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button38ActionPerformed(evt);
            }
        });
        pnl1.add(button38);

        button39.setBackground(new java.awt.Color(51, 0, 51));
        button39.setForeground(new java.awt.Color(250, 250, 250));
        button39.setLabel("D9");
        button39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button39ActionPerformed(evt);
            }
        });
        pnl1.add(button39);

        button40.setBackground(new java.awt.Color(51, 0, 51));
        button40.setForeground(new java.awt.Color(250, 250, 250));
        button40.setLabel("D10");
        button40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button40ActionPerformed(evt);
            }
        });
        pnl1.add(button40);

        button41.setBackground(new java.awt.Color(51, 51, 0));
        button41.setForeground(new java.awt.Color(250, 250, 250));
        button41.setLabel("E1");
        button41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button41ActionPerformed(evt);
            }
        });
        pnl1.add(button41);

        button42.setBackground(new java.awt.Color(51, 51, 0));
        button42.setForeground(new java.awt.Color(250, 250, 250));
        button42.setLabel("E2");
        button42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button42ActionPerformed(evt);
            }
        });
        pnl1.add(button42);

        button43.setBackground(new java.awt.Color(51, 51, 0));
        button43.setForeground(new java.awt.Color(250, 250, 250));
        button43.setLabel("E3");
        button43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button43ActionPerformed(evt);
            }
        });
        pnl1.add(button43);

        button44.setBackground(new java.awt.Color(51, 51, 0));
        button44.setForeground(new java.awt.Color(250, 250, 250));
        button44.setLabel("E4");
        button44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button44ActionPerformed(evt);
            }
        });
        pnl1.add(button44);

        button45.setBackground(new java.awt.Color(51, 51, 0));
        button45.setForeground(new java.awt.Color(250, 250, 250));
        button45.setLabel("E5");
        button45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button45ActionPerformed(evt);
            }
        });
        pnl1.add(button45);

        button46.setBackground(new java.awt.Color(51, 51, 0));
        button46.setForeground(new java.awt.Color(250, 250, 250));
        button46.setLabel("E6");
        button46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button46ActionPerformed(evt);
            }
        });
        pnl1.add(button46);

        button47.setBackground(new java.awt.Color(51, 51, 0));
        button47.setForeground(new java.awt.Color(250, 250, 250));
        button47.setLabel("E7");
        button47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button47ActionPerformed(evt);
            }
        });
        pnl1.add(button47);

        button48.setBackground(new java.awt.Color(51, 51, 0));
        button48.setForeground(new java.awt.Color(250, 250, 250));
        button48.setLabel("E8");
        button48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button48ActionPerformed(evt);
            }
        });
        pnl1.add(button48);

        button49.setBackground(new java.awt.Color(51, 51, 0));
        button49.setForeground(new java.awt.Color(250, 250, 250));
        button49.setLabel("E9");
        button49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button49ActionPerformed(evt);
            }
        });
        pnl1.add(button49);

        button50.setBackground(new java.awt.Color(51, 51, 0));
        button50.setForeground(new java.awt.Color(250, 250, 250));
        button50.setLabel("E10");
        button50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button50ActionPerformed(evt);
            }
        });
        pnl1.add(button50);

        button51.setBackground(new java.awt.Color(51, 51, 0));
        button51.setForeground(new java.awt.Color(250, 250, 250));
        button51.setLabel("F1");
        button51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button51ActionPerformed(evt);
            }
        });
        pnl1.add(button51);

        button52.setBackground(new java.awt.Color(51, 51, 0));
        button52.setForeground(new java.awt.Color(250, 250, 250));
        button52.setLabel("F2");
        button52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button52ActionPerformed(evt);
            }
        });
        pnl1.add(button52);

        button53.setBackground(new java.awt.Color(51, 51, 0));
        button53.setForeground(new java.awt.Color(250, 250, 250));
        button53.setLabel("F3");
        button53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button53ActionPerformed(evt);
            }
        });
        pnl1.add(button53);

        button54.setBackground(new java.awt.Color(51, 51, 0));
        button54.setForeground(new java.awt.Color(250, 250, 250));
        button54.setLabel("F4");
        button54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button54ActionPerformed(evt);
            }
        });
        pnl1.add(button54);

        button55.setBackground(new java.awt.Color(51, 51, 0));
        button55.setForeground(new java.awt.Color(250, 250, 250));
        button55.setLabel("F5");
        button55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button55ActionPerformed(evt);
            }
        });
        pnl1.add(button55);

        button56.setBackground(new java.awt.Color(51, 51, 0));
        button56.setForeground(new java.awt.Color(250, 250, 250));
        button56.setLabel("F6");
        button56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button56ActionPerformed(evt);
            }
        });
        pnl1.add(button56);

        button57.setBackground(new java.awt.Color(51, 51, 0));
        button57.setForeground(new java.awt.Color(250, 250, 250));
        button57.setLabel("F7");
        button57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button57ActionPerformed(evt);
            }
        });
        pnl1.add(button57);

        button58.setBackground(new java.awt.Color(51, 51, 0));
        button58.setForeground(new java.awt.Color(250, 250, 250));
        button58.setLabel("F8");
        button58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button58ActionPerformed(evt);
            }
        });
        pnl1.add(button58);

        button59.setBackground(new java.awt.Color(51, 51, 0));
        button59.setForeground(new java.awt.Color(250, 250, 250));
        button59.setLabel("F9");
        button59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button59ActionPerformed(evt);
            }
        });
        pnl1.add(button59);

        button60.setBackground(new java.awt.Color(51, 51, 0));
        button60.setForeground(new java.awt.Color(250, 250, 250));
        button60.setLabel("F10");
        button60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button60ActionPerformed(evt);
            }
        });
        pnl1.add(button60);

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 500, 250));

        pnl2.setBackground(new java.awt.Color(0, 0, 18));
        pnl2.setOpaque(false);
        pnl2.setLayout(new java.awt.GridLayout(5, 2, 5, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 250, 250));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(pnl2);
        jLabel12.setText("K e");
        pnl2.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(250, 250, 250));
        jLabel13.setText("y :");
        pnl2.add(jLabel13);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 250, 250));
        jLabel8.setLabelFor(btnBooked);
        jLabel8.setText("Booked");
        pnl2.add(jLabel8);

        btnBooked.setBackground(new java.awt.Color(250, 0, 0));
        pnl2.add(btnBooked);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 250, 250));
        jLabel9.setLabelFor(btn65);
        jLabel9.setText("R 65.00");
        pnl2.add(jLabel9);

        btn65.setBackground(new java.awt.Color(0, 51, 51));
        pnl2.add(btn65);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 250, 250));
        jLabel10.setLabelFor(btn70);
        jLabel10.setText("R 70.00");
        pnl2.add(jLabel10);

        btn70.setBackground(new java.awt.Color(51, 0, 51));
        pnl2.add(btn70);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(250, 250, 250));
        jLabel11.setLabelFor(btn75);
        jLabel11.setText("R 75.00");
        pnl2.add(jLabel11);

        btn75.setBackground(new java.awt.Color(51, 51, 0));
        pnl2.add(btn75);

        getContentPane().add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 100, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cinema-background-with-movie-objects.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 690, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new SignIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinceActionPerformed
        cmbMovie.setEnabled(false);
        edtSeats.setText("");
        edtPrice.setText("R 0.00");
        cmbTime.setEnabled(false);
        jXDatePicker1.setEnabled(false);
        
        resetSeat();
        
        switch (cmbProvince.getSelectedIndex())
        {
            case 1:
                Province("EC");
                cmbCinema.setEnabled(true);
                break;
            case 2:
                Province("FS");
                cmbCinema.setEnabled(true);
                break;
            case 3:
                Province("GT");
                cmbCinema.setEnabled(true);
                break;
            case 4:
                Province("NL");
                cmbCinema.setEnabled(true);
                break;
            case 5:
                Province("LP");
                cmbCinema.setEnabled(true);
                break;
            case 6:
                Province("MP");
                cmbCinema.setEnabled(true);
                break;
            case 7:
                Province("NC");
                cmbCinema.setEnabled(true);
                break;
            case 8:
                Province("NW");
                cmbCinema.setEnabled(true);
                break;
            case 9:
                Province("WC");
                cmbCinema.setEnabled(true);
                break;
            default:
                cmbCinema.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_cmbProvinceActionPerformed

    private void cmbCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCinemaActionPerformed
        edtSeats.setText("");
        edtPrice.setText("R 0.00");        
        cmbTime.setEnabled(false);
        jXDatePicker1.setEnabled(false);
        
        resetSeat();
        
        switch (cmbCinema.getSelectedItem().toString())
        {
            case "Nu Metro":
                Cinema("NM");
                cmbMovie.setEnabled(true);
                break;
            case "Ster Kinekor":
                Cinema("SK");
                cmbMovie.setEnabled(true);
                break;
            case "Hemingways":
                Cinema("HW");
                cmbMovie.setEnabled(true);
                break;
            case "Epic Cinemas":
                Cinema("EC");
                cmbMovie.setEnabled(true);
                break;
            case "IMAX":
                Cinema("IM");
                cmbMovie.setEnabled(true);
                break;
            case "MOVIES@":
                Cinema("MO");
                cmbMovie.setEnabled(true);
                break;
            case "Cine Centre":
                Cinema("CC");
                cmbMovie.setEnabled(true);
                break;
            case "Whale Coast Theater":
                Cinema("WC");
                cmbMovie.setEnabled(true);
                break;
            case "The Galileo":
                Cinema("GA");
                cmbMovie.setEnabled(true);
                break;
            default:
                cmbMovie.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_cmbCinemaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Seat = "A1";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Seat = "A2";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        Seat = "A3";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        Seat = "A4";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        Seat = "A5";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        Seat = "A6";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        Seat = "A7";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        Seat = "A8";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        Seat = "A9";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        Seat = "A10";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        Seat = "B1";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        Seat = "B2";
        Price = 65.00; 
        validSeat(Seat, Price);
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        Seat = "B3";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        Seat = "B4";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        Seat = "B5";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button15ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        Seat = "B6";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button16ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        Seat = "B7";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button17ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        Seat = "B8";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button18ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        Seat = "B9";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button19ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        Seat = "B10";
        Price = 65.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button20ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        Seat = "C1";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        Seat = "C2";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        Seat = "C3";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        Seat = "C4";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button24ActionPerformed

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button25ActionPerformed
        Seat = "C5";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button25ActionPerformed

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button26ActionPerformed
        Seat = "C6";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button26ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed
        Seat = "C7";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button27ActionPerformed

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button28ActionPerformed
        Seat = "C8";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button28ActionPerformed

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button29ActionPerformed
        Seat = "C9";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button29ActionPerformed

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button30ActionPerformed
        Seat = "C10";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button30ActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        Seat = "D1";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button31ActionPerformed

    private void button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button32ActionPerformed
        Seat = "D2";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button32ActionPerformed

    private void button33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button33ActionPerformed
        Seat = "D3";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button33ActionPerformed

    private void button34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button34ActionPerformed
        Seat = "D4";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button34ActionPerformed

    private void button35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button35ActionPerformed
        Seat = "D5";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button35ActionPerformed

    private void button36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button36ActionPerformed
        Seat = "D6";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button36ActionPerformed

    private void button37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button37ActionPerformed
        Seat = "D7";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button37ActionPerformed

    private void button38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button38ActionPerformed
        Seat = "D8";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button38ActionPerformed

    private void button39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button39ActionPerformed
        Seat = "D9";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button39ActionPerformed

    private void button40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button40ActionPerformed
        Seat = "D10";
        Price = 70.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button40ActionPerformed

    private void button41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button41ActionPerformed
        Seat = "E1";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button41ActionPerformed

    private void button42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button42ActionPerformed
        Seat = "E2";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button42ActionPerformed

    private void button43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button43ActionPerformed
        Seat = "E3";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button43ActionPerformed

    private void button44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button44ActionPerformed
        Seat = "E4";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button44ActionPerformed

    private void button45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button45ActionPerformed
        Seat = "E5";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button45ActionPerformed

    private void button46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button46ActionPerformed
        Seat = "E6";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button46ActionPerformed

    private void button47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button47ActionPerformed
        Seat = "E7";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button47ActionPerformed

    private void button48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button48ActionPerformed
        Seat = "E8";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button48ActionPerformed

    private void button49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button49ActionPerformed
        Seat = "E9";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button49ActionPerformed

    private void button50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button50ActionPerformed
        Seat = "E10";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button50ActionPerformed

    private void button51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button51ActionPerformed
        Seat = "F1";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button51ActionPerformed

    private void button52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button52ActionPerformed
        Seat = "F2";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button52ActionPerformed

    private void button53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button53ActionPerformed
        Seat = "F3";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button53ActionPerformed

    private void button54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button54ActionPerformed
        Seat = "F4";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button54ActionPerformed

    private void button55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button55ActionPerformed
        Seat = "F5";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button55ActionPerformed

    private void button56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button56ActionPerformed
        Seat = "F6";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button56ActionPerformed

    private void button57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button57ActionPerformed
        Seat = "F7";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button57ActionPerformed

    private void button58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button58ActionPerformed
        Seat = "F8";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button58ActionPerformed

    private void button59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button59ActionPerformed
        Seat = "F9";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button59ActionPerformed

    private void button60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button60ActionPerformed
        Seat = "F10";
        Price = 75.00;
        validSeat(Seat, Price);
    }//GEN-LAST:event_button60ActionPerformed

    private void btnAddSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSeatActionPerformed
        Amount = Amount + Price;
        edtTotal.setText("R" + String.format("%10.2f", Amount));
        
        lstSeat.add(Seat);
        edtSeats.setText(edtSeats.getText() + "\n" + Seat +"                R" + String.format("%10.2f", Price));
    }//GEN-LAST:event_btnAddSeatActionPerformed

    private void cmbMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovieActionPerformed
        resetSeat();
        cmbTime.setEnabled(false);
        
        try {
            CinemaSprintJava.DBConnection();
            
            String sql = "SELECT * FROM tbl_movies";
            Statement stmt = (Statement) CinemaSprintJava.conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);            
            rs.beforeFirst();
            
            while (rs.next())
            {
                if (rs.getString("Name").equals(cmbMovie.getSelectedItem().toString()))
                {
                    Movie = rs.getInt("ID");
                }
            }
            
            rs.close();
            CinemaSprintJava.conn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        jXDatePicker1.setEnabled(true);
    }//GEN-LAST:event_cmbMovieActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if (cmbProvince.getSelectedItem().toString().equals("<Select Province>") || 
                cmbCinema.getSelectedItem().toString().equals("<Select Cinema>") ||
                cmbMovie.getSelectedItem().toString().equals("<Select Movie>") ||
                lstSeat.size() == 0)
        {
            JOptionPane.showMessageDialog(null, "Incorrect information to proceed with purchase");
        }
        else
        {
            try {
                CinemaSprintJava.DBConnection();
                PreparedStatement ps;
                String query = "INSERT INTO tbl_sales(ContactID, ProvinceCode, CinemaID, MovieID, Seat) VALUES (?,?,?,?,?)";
                ps = CinemaSprintJava.conn.prepareStatement(query);
                ps.setInt(1, CinemaSprintJava.ID);
                ps.setString(2, Prov);
                ps.setInt(3, Cine);
                ps.setInt(4, Movie);
                
                for (int i = 0; i < lstSeat.size(); i++) {
                    ps.setString(5, lstSeat.get(i));
                    ps.executeUpdate();
                }
                
                edtSeats.setText(edtSeats.getText() + "\n------------------------------------------------------" +
                        "\nTOTAL: R" + String.format("%10.2f", Amount)); 
                
                JOptionPane.showMessageDialog(null, "Purchase successful");
                JOptionPane.showMessageDialog(null, "Please save a copy of the recipt");
                
                pnl1.setEnabled(false);
                cmbCinema.setEnabled(false);
                cmbMovie.setEnabled(false);
                cmbProvince.setEnabled(false);
                
                CinemaSprintJava.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnRemoveSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSeatsActionPerformed
        edtSeats.setText(cmbProvince.getSelectedItem().toString() + "       "
                + cmbCinema.getSelectedItem().toString() + "        " 
                + cmbMovie.getSelectedItem().toString() 
                + "\nSeats:         Price:");
        
        lstSeat.clear();
    }//GEN-LAST:event_btnRemoveSeatsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Calendar today = Calendar.getInstance();
        jXDatePicker1.setDate(today.getTime());
        jXDatePicker1.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cmbTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTimeActionPerformed
        boolean valid = true;
        Date date = jXDatePicker1.getDate();
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String dateBooked = dformat.format(date);
        String Time = cmbTime.getSelectedItem().toString(); 
        
        resetSeat();
        
        try {
            CinemaSprintJava.DBConnection();

            String sql = "SELECT Seat FROM tbl_sales WHERE CinemaID = "+Cine+" AND MovieID = "+Movie+" AND DateSlot = '"+dateBooked+"' AND TimeSlot = '"+Time+":00'";
            Statement stmt = CinemaSprintJava.conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            rs.beforeFirst();

            while (rs.next()) {
                bookedSeat.add(rs.getString("Seat"));
            } 

            Collections.sort(bookedSeat);

            for (int j = 0; j < seatButtons.length; j++) {
                if (bookedSeat.contains(seatButtons[j])){
                    validAvalibleSeat(seatButtons[j]);
                } 
            }

            rs.close();
            CinemaSprintJava.conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
        edtSeats.setText(cmbProvince.getSelectedItem().toString() + "       "
                + cmbCinema.getSelectedItem().toString() + "\n" 
                + cmbMovie.getSelectedItem().toString()
                + "  on  " + dateBooked + "  @" + Time
                + "\nSeats:         Price:");
    }//GEN-LAST:event_cmbTimeActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        cmbTime.setEnabled(true);
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn65;
    private java.awt.Button btn70;
    private java.awt.Button btn75;
    private javax.swing.JButton btnAddSeat;
    private javax.swing.JButton btnBook;
    private java.awt.Button btnBooked;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemoveSeats;
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button23;
    private java.awt.Button button24;
    private java.awt.Button button25;
    private java.awt.Button button26;
    private java.awt.Button button27;
    private java.awt.Button button28;
    private java.awt.Button button29;
    private java.awt.Button button3;
    private java.awt.Button button30;
    private java.awt.Button button31;
    private java.awt.Button button32;
    private java.awt.Button button33;
    private java.awt.Button button34;
    private java.awt.Button button35;
    private java.awt.Button button36;
    private java.awt.Button button37;
    private java.awt.Button button38;
    private java.awt.Button button39;
    private java.awt.Button button4;
    private java.awt.Button button40;
    private java.awt.Button button41;
    private java.awt.Button button42;
    private java.awt.Button button43;
    private java.awt.Button button44;
    private java.awt.Button button45;
    private java.awt.Button button46;
    private java.awt.Button button47;
    private java.awt.Button button48;
    private java.awt.Button button49;
    private java.awt.Button button5;
    private java.awt.Button button50;
    private java.awt.Button button51;
    private java.awt.Button button52;
    private java.awt.Button button53;
    private java.awt.Button button54;
    private java.awt.Button button55;
    private java.awt.Button button56;
    private java.awt.Button button57;
    private java.awt.Button button58;
    private java.awt.Button button59;
    private java.awt.Button button6;
    private java.awt.Button button60;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JComboBox<String> cmbCinema;
    private javax.swing.JComboBox<String> cmbMovie;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JTextField edtPrice;
    private javax.swing.JTextField edtSeat;
    private javax.swing.JTextArea edtSeats;
    private javax.swing.JTextField edtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnlSelection;
    // End of variables declaration//GEN-END:variables

    private void Province(String Code) {
        try {
            CinemaSprintJava.DBConnection();
            
            Prov = Code;
            
            String sql = "SELECT CineName FROM tbl_cinema WHERE (FK_ProvCode = '"+Prov+"')";
            Statement stmt = (Statement) CinemaSprintJava.conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            int i = 1;
            rs.last();
            int len = rs.getRow();
            String lables[] = new String[len+1]; 
            lables[0] = "<Select Cinema>";
            
            rs.beforeFirst();
            while (rs.next())
            {
                lables[i] = rs.getString("CineName");
                i++;
            }
            
            cmbCinema.setModel(new DefaultComboBoxModel(lables));
            
            rs.close();
            CinemaSprintJava.conn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void Cinema(String Code) {
        try {
            CinemaSprintJava.DBConnection();
            
            String CineCode = Code;
            
            String sql = "SELECT tbl_cinema.ID, tbl_movies.Name FROM cinema_movies\n" +
                          "LEFT JOIN tbl_cinema on cinema_movies.CinemaID = tbl_cinema.ID\n" + 
                          "LEFT JOIN tbl_movies on cinema_movies.MoviesID = tbl_movies.ID\n" +
                          "WHERE (tbl_cinema.CineCode = '"+CineCode+"' AND tbl_cinema.FK_ProvCode = '"+Prov+"')";
            Statement stmt = (Statement) CinemaSprintJava.conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            int i = 1;
            rs.last();
            int len = rs.getRow();
            String lables[] = new String[len+1]; 
            lables[0] = "<Select Movie>";
            
            rs.beforeFirst();
            while (rs.next())
            {
                Cine = rs.getInt("ID");
                lables[i] = rs.getString("Name");
                i++;
            }
            
            cmbMovie.setModel(new DefaultComboBoxModel(lables));
            
            rs.close();
            CinemaSprintJava.conn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void validSeat(String Seat1, double Price1) {
        boolean valid = true;
        
        if (Cine == 0 || Movie == 0)
            JOptionPane.showMessageDialog(null, "Please select a cinema and movie");
        else {
            try {
                CinemaSprintJava.DBConnection();

                String sql = "SELECT CinemaID, MovieID, Seat FROM tbl_sales WHERE CinemaID = "+Cine+" AND MovieID = "+Movie;
                Statement stmt = CinemaSprintJava.conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                rs.beforeFirst();

                while (rs.next()) {
                    String DBSeatNum = rs.getString("Seat");

                    if (Seat1.equals(DBSeatNum)) 
                    {
                        valid = false;
                    }
                } 
                
                if (valid) {
                    edtSeat.setText(Seat1);
                    edtPrice.setText("R" + String.format("%10.2f", Price1));
                } else {
                    JOptionPane.showMessageDialog(null, Seat1 + " is already booked!");
                }

                rs.close();
                CinemaSprintJava.conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }        
        }
    }

    private void validAvalibleSeat(String seatButton) {
        Component[] comp = pnl1.getComponents();
        
        for (int i=0; i<comp.length; i++) {
            if (seatButton.equals(((Button)comp[i]).getLabel())){
                ((Button)comp[i]).setBackground(new java.awt.Color(255, 0, 0));
            }
        }
    }
    
    private void resetSeat(){
        Component[] comp = pnl1.getComponents();
        
        for (int i=0; i<comp.length; i++) {
            if (i<20){
                ((Button)comp[i]).setBackground(new java.awt.Color(0, 51, 51));
            } else if (i>=20 && i<40) {
                ((Button)comp[i]).setBackground(new java.awt.Color(51, 0, 51));
            } else {
                ((Button)comp[i]).setBackground(new java.awt.Color(51, 51, 0));
            }
        }
    }
}
