/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cinemasprintjava;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Our
 */
public class SignUp extends javax.swing.JFrame {
    
      public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM tbl_contacts WHERE IDnum =?";
        
        try {
            CinemaSprintJava.DBConnection();
            
            ps = CinemaSprintJava.conn.prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        edtPassword = new javax.swing.JPasswordField();
        edtConfirm = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pbarSignUp = new javax.swing.JProgressBar();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setName("frmSignUp"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 28, -1, -1));
        getContentPane().add(edtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 108, -1));
        getContentPane().add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));
        getContentPane().add(edtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, -1));

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Enter ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 76, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Enter a Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 139, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Confirm Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 196, 110, -1));

        pbarSignUp.setStringPainted(true);
        getContentPane().add(pbarSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Red curtains.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 360, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String ID = edtID.getText();
        String Password = String.valueOf(edtPassword.getPassword());
        String Confirm = String.valueOf(edtConfirm.getPassword());
        boolean valid = true;
                
        if(ID.equals("") || ID.length() != 13)
        {
            JOptionPane.showMessageDialog(null, "Add your ID or check it");
            valid = false;
            pbarSignUp.setValue(pbarSignUp.getValue() + 20);
            pbarSignUp.setString(Integer.toString(pbarSignUp.getValue()) + "% Invalid");
        }
        
        if(Password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
            valid = false;
            pbarSignUp.setValue(pbarSignUp.getValue() + 20);
            pbarSignUp.setString(Integer.toString(pbarSignUp.getValue()) + "% Invalid");
        }
        
        
        if(!Password.equals(Confirm))
        {
            JOptionPane.showMessageDialog(null, "Retype The Password Again");
            valid = false;
            pbarSignUp.setValue(pbarSignUp.getValue() + 20);
            pbarSignUp.setString(Integer.toString(pbarSignUp.getValue()) + "% Invalid");
        }
            
        if(checkUsername(ID))
        {
            JOptionPane.showMessageDialog(null, "This ID Already Exist");
            valid = false;
            pbarSignUp.setValue(pbarSignUp.getValue() + 20);
            pbarSignUp.setString(Integer.toString(pbarSignUp.getValue()) + "% Invalid");
        }
            
        for (int i = 0; i < ID.length(); i++) 
        {
            if (!Character.isDigit(ID.charAt(i))) {
                valid = false;
                pbarSignUp.setValue(pbarSignUp.getValue() + 20);
                pbarSignUp.setString(Integer.toString(pbarSignUp.getValue()) + "% Invalid");
            }
        }
        
        if (valid)
        {
            try {
                CinemaSprintJava.DBConnection();
                PreparedStatement ps;
                String query = "INSERT INTO tbl_contacts(IDnum, Password) VALUES (?,?)";
                ps = CinemaSprintJava.conn.prepareStatement(query);

                ps.setString(1, ID);
                ps.setString(2, Password);

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "New User Add");
                    SignIn frmSignIn = new SignIn();
                    frmSignIn.setVisible(true);
                    this.dispose();
                }

                CinemaSprintJava.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Failed to Add User");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new SignIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPasswordField edtConfirm;
    private javax.swing.JTextField edtID;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar pbarSignUp;
    // End of variables declaration//GEN-END:variables
}
